import { StyleSheet } from '@react-pdf/renderer'

export const CHART_COLORS = [
  '#38bdf8',
  '#10b981',
  '#f59e0b',
  '#f97316',
  '#a855f7',
  '#ec4899',
  '#06b6d4',
  '#84cc16',
  '#eab308',
  '#6366f1',
]

export const pdfStyles = StyleSheet.create({
  page: {
    backgroundColor: '#020617',
    color: '#e2e8f0',
    fontFamily: 'Helvetica',
    paddingTop: 36,
    paddingBottom: 40,
    paddingHorizontal: 44,
  },
  headerRule: {
    height: 3,
    width: 56,
    backgroundColor: '#10b981',
    marginBottom: 14,
  },
  footer: {
    position: 'absolute',
    bottom: 18,
    right: 44,
    fontSize: 8,
    color: '#64748b',
  },
  title: {
    fontSize: 22,
    fontFamily: 'Helvetica-Bold',
    color: '#f8fafc',
    marginBottom: 6,
    lineHeight: 1.2,
  },
  titleAccent: {
    color: '#10b981',
    fontFamily: 'Helvetica-Bold',
  },
  highlight: {
    fontSize: 13,
    fontFamily: 'Helvetica-Bold',
    color: '#10b981',
    marginBottom: 8,
  },
  subtitle: {
    fontSize: 11,
    color: '#94a3b8',
    lineHeight: 1.45,
    marginBottom: 10,
    maxWidth: '100%',
  },
  quote: {
    fontSize: 11,
    fontStyle: 'italic',
    color: '#cbd5e1',
    borderLeftWidth: 3,
    borderLeftColor: 'rgba(16,185,129,0.55)',
    paddingLeft: 12,
    marginTop: 8,
    marginBottom: 10,
    lineHeight: 1.45,
  },
  intro: {
    fontSize: 11,
    color: '#cbd5e1',
    lineHeight: 1.5,
    marginBottom: 12,
  },
  sectionHeading: {
    fontSize: 12,
    fontFamily: 'Helvetica-Bold',
    color: '#f8fafc',
    marginTop: 10,
    marginBottom: 6,
  },
  bulletLine: {
    fontSize: 10,
    color: '#cbd5e1',
    lineHeight: 1.45,
    marginBottom: 5,
    paddingLeft: 10,
  },
  bulletMarker: {
    color: '#10b981',
  },
  bold: {
    fontFamily: 'Helvetica-Bold',
    color: '#f8fafc',
  },
  continued: {
    fontSize: 9,
    color: '#64748b',
    marginBottom: 10,
  },
  card: {
    borderWidth: 1,
    borderColor: '#334155',
    borderStyle: 'solid',
    backgroundColor: '#0f172a',
    padding: 10,
    marginBottom: 8,
    borderRadius: 4,
  },
  cardTitle: {
    fontSize: 9,
    fontFamily: 'Helvetica-Bold',
    color: '#f8fafc',
    marginBottom: 6,
    lineHeight: 1.35,
  },
  cardSource: {
    fontSize: 7,
    color: '#64748b',
    marginTop: 6,
  },
  row: { flexDirection: 'row', alignItems: 'flex-start' },
  rowGap: { flexDirection: 'row', gap: 10 },
  legendItem: { fontSize: 7, color: '#cbd5e1', marginBottom: 2 },
  pillarStat: {
    fontSize: 18,
    fontFamily: 'Helvetica-Bold',
    color: '#10b981',
  },
  verdictBox: {
    borderWidth: 1,
    borderColor: 'rgba(16,185,129,0.35)',
    backgroundColor: 'rgba(16,185,129,0.08)',
    padding: 10,
    marginTop: 8,
  },
  verdictLabel: {
    fontSize: 8,
    fontFamily: 'Helvetica-Bold',
    color: '#94a3b8',
    textTransform: 'uppercase',
    marginBottom: 4,
  },
  verdictText: {
    fontSize: 12,
    fontFamily: 'Helvetica-Bold',
    color: '#10b981',
    lineHeight: 1.35,
  },
  thesis: {
    fontSize: 9,
    color: '#94a3b8',
    lineHeight: 1.45,
    marginTop: 8,
  },
  h2small: {
    fontSize: 9,
    fontFamily: 'Helvetica-Bold',
    color: '#94a3b8',
    textTransform: 'uppercase',
    marginBottom: 6,
    letterSpacing: 0.5,
  },
  tagPill: {
    fontSize: 7,
    color: '#e2e8f0',
    backgroundColor: '#1e293b',
    paddingHorizontal: 6,
    paddingVertical: 3,
    marginRight: 4,
    marginBottom: 4,
    borderRadius: 3,
  },
  tableHeader: {
    flexDirection: 'row',
    backgroundColor: '#1e293b',
    borderBottomWidth: 1,
    borderBottomColor: '#334155',
    paddingVertical: 6,
    marginTop: 6,
  },
  tableHeaderCell: {
    fontSize: 7,
    fontFamily: 'Helvetica-Bold',
    color: '#f8fafc',
  },
  tableRow: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(51,65,85,0.5)',
    paddingVertical: 4,
  },
  tableCell: { fontSize: 7, color: '#cbd5e1' },
  recommendationsBox: {
    borderWidth: 2,
    borderColor: 'rgba(16,185,129,0.55)',
    backgroundColor: 'rgba(16,185,129,0.08)',
    padding: 10,
    marginTop: 8,
  },
})
